import 'dart:io';

import 'package:drift/drift.dart' as drift;
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:shopping_assist/core/database/database.dart';
import 'package:shopping_assist/features/items/repositories/items_repository.dart';
import 'package:shopping_assist/core/widgets/item_image_picker.dart';

class EditItemDialog extends StatefulWidget {
  final Item item;
  const EditItemDialog({super.key, required this.item});

  @override
  State<EditItemDialog> createState() => _EditItemDialogState();
}

class _EditItemDialogState extends State<EditItemDialog> {
  late TextEditingController _controller;
  String? _imagePath;

  final List<String> _tempImagePaths = [];
  bool _isSaved = false;

  @override
  void initState() {
    super.initState();
    _controller = TextEditingController(text: widget.item.name);
    _imagePath = widget.item.imagePath;
  }

  @override
  void dispose() {
    _controller.dispose();
    _cleanupTempImages();
    super.dispose();
  }

  void _cleanupTempImages() {
    for (final path in _tempImagePaths) {
      // Don't delete the image if the user chose to save it
      if (_isSaved && path == _imagePath) continue;
      final file = File(path);
      if (file.existsSync()) file.deleteSync();
    }
  }

  void _submit() {
    final name = _controller.text.trim();
    if (name.isNotEmpty) {
      _isSaved = true;
      context.read<ItemsRepository>().updateItem(
        widget.item.id,
        name: name,
        imagePath: drift.Value(_imagePath),
      );
      Navigator.pop(context);
    }
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text('Edit Item'),
      // SizedBox to constrain the column width securely
      content: SizedBox(
        width: double.maxFinite,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(controller: _controller, autofocus: true),
            const SizedBox(height: 16),
            ItemImagePicker(
              imagePath: _imagePath,
              onChanged: (path) {
                setState(() {
                  _imagePath = path;
                  // If a new image was generated by ImagePicker, add it to our tracking list
                  if (path != null && path != widget.item.imagePath) {
                    _tempImagePaths.add(path);
                  }
                });
              },
            ),
          ],
        ),
      ),
      actions: [
        TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
        FilledButton(onPressed: _submit, child: const Text('Save')),
      ],
    );
  }
}
